PANDAS

In [1]:
import pandas as pd
import numpy as np

In [2]:
#pandas handle 2 types of data that are series and data frame

In [7]:
s = pd.Series([1, 2, 3, np.nan, 5])
s

0    1.0
1    2.0
2    3.0
3    NaN
4    5.0
dtype: float64

In [10]:
#converting numpy array with pandas dataframe
arr = np.arange(10)
arr = arr.reshape((5, 2))

df = pd.DataFrame(arr, columns = list("ab"))
df

   a  b
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9

In [12]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [15]:
# to know the data types of the columns 
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [19]:
#to view the head and tail of the data
print("Head: ")
print(df2.head(2))
print("Tail: ")
print(df2.tail(2))

Head:
     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
Tail:
     A          B    C  D      E    F
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [22]:
#to view the index and column of data frame
print("index: ")
print(df2.index)
print("columns: ")
print(df2.columns)

index:
Index([0, 1, 2, 3], dtype='int64')
columns:
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [23]:
#For to convert pandas to numpy
print(df2.to_numpy())

[[1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'test' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'train' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'test' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'train' 'foo']]

In [24]:
#To get statistics of data
print(df2.describe())

         A                    B    C    D
count  4.0                    4  4.0  4.0
mean   1.0  2013-01-02 00:00:00  1.0  3.0
min    1.0  2013-01-02 00:00:00  1.0  3.0
25%    1.0  2013-01-02 00:00:00  1.0  3.0
50%    1.0  2013-01-02 00:00:00  1.0  3.0
75%    1.0  2013-01-02 00:00:00  1.0  3.0
max    1.0  2013-01-02 00:00:00  1.0  3.0
std    0.0                  NaN  0.0  0.0

In [25]:
#We can transpose of the dataframe 
df2.T

,0,1,2,3
A,1.0,1.0,1.0,1.0
B,2013-01-02 00:00:00,2013-01-02 00:00:00,2013-01-02 00:00:00,2013-01-02 00:00:00
C,1.0,1.0,1.0,1.0
D,3,3,3,3
E,test,train,test,train
F,foo,foo,foo,foo

In [ ]:
#For further few steps we are going to use df
df

   a  b
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9

In [31]:
#sort index based on rows
df.sort_index(axis=0, ascending=False)

   a  b
4  8  9
3  6  7
2  4  5
1  2  3
0  0  1

In [32]:
#sort index based on columns
df.sort_index(axis=1, ascending=False)

   b  a
0  1  0
1  3  2
2  5  4
3  7  6
4  9  8

In [ ]:
#we can also sort values by column
df.sort_values(by="a", ascending=False)

   a  b
4  8  9
3  6  7
2  4  5
1  2  3
0  0  1

In [ ]:
#selecting row matching label
df.loc[0:1] # it is label slicing it means it searches the labels from 0 to 1, not work as range

   a  b
0  0  1
1  2  3

In [41]:
df.loc[:, ["b"]]

   b
0  1
1  3
2  5
3  7
4  9

In [44]:
#selection by position
df.iloc[0:2, 0:1]

   a
0  0
1  2

In [45]:
df.iloc[[0], [1]]

   b
0  1

In [46]:
#Filtering
df[df.loc[:, "a"]>3]

   a  b
2  4  5
3  6  7
4  8  9

In [53]:
df[df["a"].isin([2])]

   a  b
1  2  3

In [47]:
#Getting values that met cindition
df[df>2]

     a    b
0  NaN  NaN
1  NaN  3.0
2  4.0  5.0
3  6.0  7.0
4  8.0  9.0

In [49]:
#setting values at particular index and column
df.at[0,"a"] = 10
df

    a  b
0  10  1
1   2  3
2   4  5
3   6  7
4   8  9

In [50]:
#setting values at particular positions
df.iat[0, 0] = 20
df

    a  b
0  20  1
1   2  3
2   4  5
3   6  7
4   8  9

In [54]:
#Replacing values that are satisfying condition
df[df>5] = -df
df

    a  b
0 -20  1
1   2  3
2   4  5
3  -6 -7
4  -8 -9

In [55]:
df = df[df<0]

In [56]:
df

      a    b
0 -20.0  NaN
1   NaN  NaN
2   NaN  NaN
3  -6.0 -7.0
4  -8.0 -9.0

In [57]:
#dropping missing values
df.dropna(how="any")

     a    b
3 -6.0 -7.0
4 -8.0 -9.0

In [58]:
#filling missing values
df.fillna(1)

      a    b
0 -20.0  1.0
1   1.0  1.0
2   1.0  1.0
3  -6.0 -7.0
4  -8.0 -9.0

In [59]:
#Finding each value is nan or not
df.isna()

       a      b
0  False   True
1   True   True
2   True   True
3  False  False
4  False  False

In [60]:
#doing aggregations
df.agg(lambda x:x.sum())

a   -34.0
b   -16.0
dtype: float64

In [62]:
#transforming values
df.transform(lambda x: x*10)

       a     b
0 -200.0   NaN
1    NaN   NaN
2    NaN   NaN
3  -60.0 -70.0
4  -80.0 -90.0

In [63]:
df.value_counts()

a     b
-8.0  -9.0    1
-6.0  -7.0    1
Name: count, dtype: int64

In [65]:
#String methods for series
s = pd.Series([1,2,3,4,5, np.nan, "Abc", "TEST"])
s.str.lower()

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
5     NaN
6     abc
7    test
dtype: object

In [66]:
#Merging 2 data frames
left = pd.DataFrame({"key": ["foo", "foo"], "lval": [1, 2]})

right = pd.DataFrame({"key": ["foo", "foo"], "rval": [4, 5]})

mergedDf = pd.merge(left, right, on="key")
mergedDf

   key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

In [ ]:
#grouping 
df = pd.DataFrame(
    {
        "A": ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
        "B": ["one", "one", "two", "three", "two", "two", "one", "three"],
        "C": np.random.randn(8),
        "D": np.random.randn(8),
    }
)

df.groupby("B")[["C", "D"]].sum() # it specifies after grouping want tonly C, D columns as they are like integers and sum operation can be made.

              C         D
B
one    2.391765 -0.045479
three  1.495658  0.217028
two   -1.549508 -1.945067

In [70]:
#handling categorical values
df = pd.DataFrame(
    {"id": [1, 2, 3, 4, 5, 6], "raw_grade": ["a", "b", "b", "a", "a", "e"]}
)
df["grade"] = df["raw_grade"].astype("category")

df["grade"]

0    a
1    b
2    b
3    a
4    a
5    e
Name: grade, dtype: category
Categories (3, object): ['a', 'b', 'e']

In [73]:
#we can replace categorical values with some meaningful names
categoricalReplacements = ["Good", "OK", "Bad"]
df["grade"].cat.rename_categories(categoricalReplacements)

0    Good
1      OK
2      OK
3    Good
4    Good
5     Bad
Name: grade, dtype: category
Categories (3, object): ['Good', 'OK', 'Bad']